export const companyEntityTypes = {
  'limited-liability-company': 'Limited Liability Partnership',
  'public-limited-company': 'Public Limited Company ',
  'private-limited-company': 'Private Limited Company',
};

export const IndustrySectors = [
  { slug: 'information-technology', name: 'Information Technology' },
  { slug: 'healthcare', name: 'Healthcare' },
  { slug: 'finance', name: 'Finance' },
  { slug: 'manufacturing', name: 'Manufacturing' },
  { slug: 'retail', name: 'Retail' },
  { slug: 'transportation', name: 'Transportation' },
  { slug: 'energy', name: 'Energy' },
  { slug: 'hospitality', name: 'Hospitality' },
  { slug: 'education', name: 'Education' },
  { slug: 'media-and-entertainment', name: 'Media and Entertainment' },
  { slug: 'telecommunications', name: 'Telecommunications' },
  { slug: 'automotive', name: 'Automotive' },
  { slug: 'real-estate', name: 'Real Estate' },
  { slug: 'agriculture', name: 'Agriculture' },
  { slug: 'pharmaceuticals', name: 'Pharmaceuticals' },
  { slug: 'biotechnology', name: 'Biotechnology' },
  { slug: 'tourism', name: 'Tourism' },
  { slug: 'environmental-services', name: 'Environmental Services' },
  { slug: 'sports', name: 'Sports' },
  { slug: 'fashion', name: 'Fashion' },
];

export const BusinessEntityTypes = [
  {
    slug: 'limited-liability-company',
    name: 'Limited Liability Company (Ltd)',
  },
  { slug: 'public-limited-company', name: 'Public Limited Company (PLC)' },
  { slug: 'private-limited-company', name: 'Private Limited Company' },
  // { slug: "sole-proprietorship", name: "Sole Proprietorship" },
  // { slug: "partnership", name: "Partnership" },
  // { slug: "cooperative", name: "Cooperative" },
  // { slug: "non-governmental-organization", name: "Non-Governmental Organization (NGO)" },
  // { slug: "government-agency", name: "Government Agency" },
  // { slug: "public-corporation", name: "Public Corporation" },
  // { slug: "state-owned-enterprise", name: "State-Owned Enterprise (SOE)" },
  // { slug: "public-private-partnership", name: "Public-Private Partnership (PPP)" },
  // { slug: "subsidiary", name: "Subsidiary" },
  // { slug: "holding-company", name: "Holding Company" },
  // { slug: "technology-startup", name: "Technology Startup" },
  // { slug: "family-owned", name: "Family-Owned Business" },
  // { slug: "microfinance-institution", name: "Microfinance Institution" },
  // { slug: "educational-institution", name: "Educational Institution" },
  // { slug: "religious-organization", name: "Religious Organization" },
  // { slug: "community-based-organization", name: "Community-Based Organization (CBO)" },
];
